# SPDX-FileCopyrightText: (c) 2026 Joel Winarske
# SPDX-License-Identifier: MIT

[package]
name = "drmkit-cursor"
description = "Cursor themes and rasterized cursors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
drmkit-core = { workspace = true }
drmkit-fmt = { workspace = true }
drmkit-planes = { workspace = true }
thiserror = { workspace = true, features = ["std"] }

[dev-dependencies]
drm = { workspace = true }

[lints]
workspace = true
